### ISSUE TITLE
Hiding channel feature doesn't work

### ISSUE THREAD

**Issue by dlik** [zoemartin01/Pirates-Bot#8]
IIRC, there are text channels, that should only be visible, if one is connected to their respective voice channel.
In my case, though, I can see all text channels, no matter whether I am connected to any of the voice channels, or not.
This is what it looks like:

![grafik](https://user-images.githubusercontent.com/1255784/96439224-f8e82800-1206-11eb-9b3b-550ab94d80ae.png)

Pls fix owo uwu

DLIK

**Comment by zoemartin01** [comment]
The feature works. You are an administrator and see every channel regardless of overrides.
